theme: jekyll-theme-cayman
title: Métodos Numéricos con Python - Parte 1 Cálculo Numérico
description: Aprende todos los algoritmos de aproximación, interpolación, derivación e integración numérica de funciones en Python.
url: https://www.udemy.com/course/draft/3739518/?couponCode=92A16B706AA151705D35
link: https://www.udemy.com/course/draft/3739518/?couponCode=92A16B706AA151705D35